# Generated by Django 4.1 on 2022-09-29 19:40

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('total_rating_score', models.IntegerField(default=5)),
                ('avg_rating_score', models.IntegerField(default=0)),
                ('constituency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allRentals.constituency')),
                ('landlord', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allRentals.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allRentals.constituency')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allRentals.ward')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('user_msg', models.TextField(blank=True, max_length=400)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('rental', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='allRentals.rental')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='village',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ward', chained_model_field='ward', on_delete=django.db.models.deletion.CASCADE, to='allRentals.village'),
        ),
        migrations.AddField(
            model_name='rental',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='constituency', chained_model_field='constituency', on_delete=django.db.models.deletion.CASCADE, to='allRentals.ward'),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='pics')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allRentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allRentals.rental')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.BooleanField(default=False)),
                ('booked', models.BooleanField(default=False)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allRentals.rental')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
