# Generated by Django 4.1 on 2022-09-14 11:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0002_userfeedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='rental',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='constituency', chained_model_field='constituency', on_delete=django.db.models.deletion.CASCADE, to='allRentals.ward'),
        ),
        migrations.AlterField(
            model_name='village',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allRentals.ward'),
        ),
        migrations.AddField(
            model_name='rental',
            name='constituency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allRentals.constituency'),
        ),
        migrations.AddField(
            model_name='ward',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allRentals.constituency'),
        ),
    ]
