# Generated by Django 4.1 on 2022-09-17 14:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0004_village_constituency_alter_village_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='constituency', chained_model_field='constituency', on_delete=django.db.models.deletion.CASCADE, to='allRentals.ward'),
        ),
    ]
