# Generated by Django 4.1 on 2022-09-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0005_alter_village_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allRentals.constituency'),
        ),
        migrations.AlterField(
            model_name='village',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allRentals.ward'),
        ),
    ]
