# Generated by Django 4.1 on 2022-09-19 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0006_alter_village_constituency_alter_village_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='rental',
            name='user_msg',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
