# Generated by Django 4.1 on 2022-09-20 07:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allRentals', '0007_rental_score_rental_user_msg_delete_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user_msg',
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('avg_score', models.IntegerField()),
                ('user_msg', models.TextField(blank=True, max_length=400)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('rental', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='allRentals.rental')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
