# Generated by Django 4.1 on 2022-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0008_remove_rental_score_remove_rental_user_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
