# Generated by Django 4.1 on 2022-09-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0009_userfeedback_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='avg_score',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='total_score',
        ),
        migrations.AddField(
            model_name='rental',
            name='avg_rating_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_rating_score',
            field=models.IntegerField(default=0),
        ),
    ]
