# Generated by Django 4.1 on 2022-09-23 07:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0011_alter_rental_total_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='content',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
