# Generated by Django 4.1 on 2022-09-23 07:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0012_rental_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='content',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
    ]
