# Generated by Django 4.1 on 2022-09-23 11:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0013_alter_rental_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
