# Generated by Django 4.1 on 2022-09-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0014_alter_rental_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='desc',
        ),
    ]
