# Generated by Django 4.1 on 2022-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0015_remove_rental_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='availability',
            field=models.IntegerField(),
        ),
    ]
