# Generated by Django 4.1 on 2022-09-29 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allRentals', '0017_favorite_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
